config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end

  root to: 'splash#index'

  devise_for :users

  resources :purchases
  resources :categories
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Purchase, user: user
    can :manage, Category, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :icon, presence: true

  belongs_to :user
  has_and_belongs_to_many :purchases

  def amount
    purchases.sum('amount')
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates :name, :amount, :categories, presence: true, length: { maximum: 100 }
  validates :amount, numericality: { greater_than: 0 }

  belongs_to :user
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true, length: { maximum: 100 }
  validates :email, uniqueness: true

  has_many :purchases
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show]

  def index
    @categories = current_user.categories
  end

  def show
    @purchases = @category.purchases.order(created_at: 'desc')
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_category
    @category = Category.includes(:purchases).find(params[:id])
  end

  def category_params
    params.fetch(:category, {}).permit(:name, :icon)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  load_and_authorize_resource

  def index
    redirect_to categories_url
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase.categories.first }
      else
        format.html { render :new }
      end
    end
  end

  private

  def purchase_params
    params.fetch(:purchase, {}).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<li>
  <%= link_to category_url(category), class: "flex-row data-row link" do %>
    <div class="flex-row mr-auto gap-10">
      <%= image_tag(category.icon) %>
      <div class="flex-col justify-between">
        <span><%= category.name %></span>
        <span><%= category.created_at.strftime("%d %b %Y") %></span>
      </div>
    </div>
    <span class="text-bold">$<%= category.amount %></span>
  <% end %>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <div class="header flex-row align-center mt-10">
    <%= render "shared/back_button" %>
    <h2 class="mr-auto ml-auto">ADD NEW CATEGORY</h2>
    <div class="actions">
      <%= form.submit "Save"%>
    </div>
  </div>
  <div class="field">
    <%= form.text_field :name, autofocus: true, placeholder: "Name", required: true, class: "w-full" %>
  </div>
  <div class="field">
    <%= form.url_field :icon, placeholder: "Icon", required: true, class: "w-full" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="container">
  <div class="header flex-row align-center mt-10">
    <span class="material-icons">menu</span>
    <h2 class="mr-auto ml-auto">CATEGORIES</h2>
    <span class="material-icons">search</span>
  </div>
  <ul class="flex-col list-col gap-10">
    <%= render @categories %>
  </ul>
  <div class="list-button">
    <%= link_to 'ADD NEW CATEGORY', new_category_path %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="container">
  <div class="header flex-row align-center mt-10">
    <%= render "devise/shared/back_button" %>
    <h2 class="mr-auto ml-auto">PURCHASES</h2>
  </div>
  <span class="total link text-bold">TOTAL: $<%= @category.amount %></span>
  <ul class="flex-col purchases-list-col list-col gap-10">
    <%= render 'purchases/index', locals: { purchases: @purchases } %>
  </ul>
  <div class="list-button">
    <%= link_to 'ADD NEW PURCHASE', new_purchase_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgetapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <div class="header flex-row align-center mt-10">
    <%= render "shared/back_button" %>
    <h2 class="mr-auto ml-auto">ADD NEW PURCHASE</h2>
    <div class="actions">
      <%= form.submit "Save"%>
    </div>
  </div>
  <div class="field">
    <%= form.text_field :name, autofocus: true, placeholder: "Name", required: true, class: "w-full" %>
  </div>
  <div class="field">
    <%= form.number_field :amount, placeholder: "Amount", required: true, class: "w-full" %>
  </div>
  <div class="field">
    <%= form.collection_select :category_ids, current_user.categories.order(:name), :id, :name, {}, { multiple: true, class: "w-full"} %>
  </div>
<% end %>

app/views/purchases/_index.html.erb
<%= render @purchases %>

app/views/purchases/_purchase.html.erb
<li class="flex-row data-row link justify-between">
  <div class="flex-col justify-between gap-10">
    <span><%= purchase.name %></span>
    <span><%= purchase.created_at.strftime("%d %b %Y") %></span>
  </div>
  <span class="text-bold">$<%= purchase.amount %></span>
</li>

app/views/purchases/new.html.erb
<%= render 'form', purchase: @purchase %>

app/views/shared/_back_button.html.erb
<%= link_to url_for(:back) do %>
  <span class="material-icons">arrow_back</span>
<% end %>

app/views/splash/index.html.erb
<div class="screen flex-col align-center vh-full">
  <h1 class="mt-auto">Budget on Rails</h1>
  <div class="flex-col mt-auto text-center w-full gap-10">
    <%= link_to 'LOG IN', new_user_session_url, class:"link link-main" %>
    <%= link_to 'SIGN UP', new_user_registration_url, class: "link"%>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>